### ISSUE TITLE
Fix the card when they are lots of speakers

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#10]
On the card we should only display a few speakers to prevent such layout

<img width="730" alt="CleanShot 2023-06-17 at 07 31 11@2x" src="https://github.com/adrienpoly/rubyvideo/assets/7847244/3915a8aa-6430-4c21-9cbf-d7f59d795236">

**Comment by enderahmetyurt** [comment]
@adrienpoly May I get it? 🫡

**Comment by adrienpoly** [comment]
all yours
