### ISSUE TITLE
Fix responsive issues with topics

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#137]
![IMG_9091](https://github.com/user-attachments/assets/4a2df6ef-98f6-4415-9eec-bdb1f2c8dcd6)
![IMG_9090](https://github.com/user-attachments/assets/f538ad64-dec2-4b48-8945-c977c662f9bc)

**Comment by marcoroth** [comment]
Whoops, I guess I was too excited to move this forward 😅

**Comment by adrienpoly** [comment]
don't worry. I was reviewed this from my phone and added this issue to not forget. Will probably fix it now
