### ISSUE TITLE
Add `slides_url` to `Talk` model

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#153]
I noticed that some of the talks have an URL to the slides in the description. Maybe we can add that to the `Talk` model and link/embed them in a nice way next to the video.

For the Ruby Unconf talks (#114) I added a `slides_url` field to the YAML files where I had it available.

**Comment by adrienpoly** [comment]
yes we can try to add this field. I am afraid the links might get broken at some point 
On the other side I would like to avoid hosting files if possible so a link is the best solution for now
