### ISSUE TITLE
Show Speaker Avatar/Name on Talk Show Page

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#154]
Right now there is no way to get to the speaker page from a talk show page. Ideally we can do something like YouTube, where we show the channel (or in our case speaker(s)) on the talk page, so that you can go to the speaker page to see all talks of that person.

![CleanShot 2024-08-21 at 01 34 53](https://github.com/user-attachments/assets/898d1e68-353d-4a2c-af40-7bff782b3f6c)

**Comment by marcoroth** [comment]
Dropping this here for inspiration:

![Talk Show@2x](https://github.com/user-attachments/assets/56c086d3-12dc-428e-aa64-25ccc36ea9a8)

**Comment by adrienpoly** [comment]
lots of great ideas in this design. 
I much prefer this version for the speaker name compare to #163. I think it covers 99% of the cases

**Comment by marcoroth** [comment]
Yeah agreed. However, I think #163 still makes sense for when it's more than one speaker, like panels/discussions/interviews/grouped lightning talks, etc.

**Comment by jmarsh24** [comment]
I took a stab at this one. I modified the discussed design and came up with a solution that I think makes sense. It seemed a bit misleading to group the event and user together but when you select it takes you to the speaker page and not the event.

So I separated them so you can go to the event page and also the speaker.

https://github.com/user-attachments/assets/ac68a893-4591-4cf1-aaca-e7d0b06010da

**Comment by marcoroth** [comment]
@jmarsh24 nice! Good idea! I like that you separated the event name/link from the speaker name 👍🏼
