### ISSUE TITLE
Enable or remove `activerecord-enhancedsqlite3-adapter` gem

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#171]
From what I can tell it seems that the `activerecord-enhancedsqlite3-adapter` gem is not enabled and doing anything.

I think we should either remove the gem or enable it so we can make use of it.

/cc @adrienpoly

**Comment by adrienpoly** [comment]
Oh I though the only thing required was to include it to benefits from a few optimisations that were not upstreamed yet to Rails

Is this adapter causing this issue with SolidQueue database being corrupted when doing crtl+c twice?

**Comment by marcoroth** [comment]
I don't think that the gem is causing the Ctrl+C issue.

**Comment by marcoroth** [comment]
I guess we can close this since we are on Rails 8 and removed the gem in https://github.com/adrienpoly/rubyvideo/commit/af9f06a454002164caff8820d16bb78c4d1f4d23
