### ISSUE TITLE
Conference Schedule Page

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#184]
Similar to #181, but showing the schedule in full-width on the conference page. This is probably more relevant for multi-track/multi-day conference than it is for single-track/single-day conferences.

![Conference Show Schedule@2x](https://github.com/user-attachments/assets/b95cf79f-4a55-4ce9-895a-0fad3aa963c8)

**Comment by marcoroth** [comment]
This might also give us the opportunity to link to "videos" like "Conference Welcome", "City Pitches" and other videos which might not technically be talks. We could hide these from all regular pages, but link from the conference schedule to them.

**Comment by adrienpoly** [comment]
how do you see this. A screen capture?

**Comment by marcoroth** [comment]
No, I was just lazy in the mockup 😅

I was thinking something like in https://github.com/adrienpoly/rubyvideo/issues/181 but with multiple columns for multiple tracks when needed.

Maybe we could use the "brand" color for a conference to color the boxes accordingly to give it a nice touch.

**Comment by marcoroth** [comment]
@alexanderadam also introduced me to http://frab.github.io/frab/, which has somewhat of a schedule standard we could support, you can embed the schudule in any schedule app.
