### ISSUE TITLE
Implement Streaming Service-like Hero on Homepage

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#187]
It would be fun to add a Streaming Service-like hero section of recent conferences on the homepage.

For each conference would need
* a background color
* a transparent version of the conference logo
* description copy
* list of keynote speakers with pictures (we should already have that)

![CleanShot 2024-09-09 at 13 36 20](https://github.com/user-attachments/assets/956adc4a-4af5-4431-bd78-cdcacfde6d9a)

**Comment by jmarsh24** [comment]
@marcoroth Was this fixed by #300 ?

**Comment by marcoroth** [comment]
Yup, thanks @jmarsh24! 🙌🏼
