### ISSUE TITLE
Black bands on videos cards

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#20]
The Youtube thumbnails have black bands on the top/bottom of the image. 
Those bands should be hidden by the CSS

Looking at https://github.com/adrienpoly/rubyvideo/pull/19 I could spot the card sometime will show the black bands (sometimes not!!!).

I think it is mostly occurring on Safari

<img width="1281" alt="CleanShot 2023-06-21 at 09 14 19@2x" src="https://github.com/adrienpoly/rubyvideo/assets/7847244/5230145f-dc6a-4093-a7ad-b5eca57d1d92">

**Comment by adrienpoly** [comment]
This must be a tricky CSS thing for Safari. I quickly searched for a solution but could not find anything obvious. would love help on that one

**Comment by Oli0li** [comment]
Hello @adrienpoly, I just looked into this today and gave it a try with PR https://github.com/adrienpoly/rubyvideo/pull/55.
