### ISSUE TITLE
Improve pagination styles

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#210]
https://www.rubyvideo.dev/talks

![CleanShot 2024-09-23 at 14 32 25@2x](https://github.com/user-attachments/assets/bc69f3e0-b5b7-45a7-a476-9ca6c790f383)

**Comment by adrienpoly** [comment]
Good catch. I think there has been a regression here maybe a recent upgrade of Pagy ??

**Comment by adrienpoly** [comment]
This been said I really wonder if we should keep the pagination. Could be nice to get an infinite scroll to replace the pagination
