### ISSUE TITLE
Feature Request: Sort Talks Menu search by publication year

### ISSUE THREAD

**Issue by sarvaiyanidhi** [adrienpoly/rubyvideo#219]
First, I'd like to express my appreciation for rubyvideo.dev. It's an invaluable resource for the Ruby community, providing easy access to conference talks.

When using the [search](https://www.rubyvideo.dev/talks?q=hotwire) function to find videos on specific topics, I've noticed that the results are not sorted by the year of publication. This makes it challenging to quickly find the most recent talks on a given subject.

Could we implement a default sorting mechanism that displays the most recent videos first in the search results? This would help users access the latest information

**Comment by adrienpoly** [comment]
I agree this would be a great improvement
