### ISSUE TITLE
Latest Rails World Talks

### ISSUE THREAD

**Issue by jmarsh24** [adrienpoly/rubyvideo#221]
The latest Rails World 2024 just occurred and the front page of rubyvideo.dev doesn't have it. The design and latest talk algorithm should be updated to catch trending videos like this.

https://www.youtube.com/watch?v=olxoNDBp6Rg
https://www.youtube.com/watch?v=zPBbHu-BKpQ
https://www.youtube.com/watch?v=-cEn_83zRFw

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/a5e648c0-2d0e-4200-8e57-a1ac6a43ffd6">

**Comment by adrienpoly** [comment]
Talks are added manually with https://github.com/adrienpoly/rubyvideo/blob/main/docs/contributing.md

We will add them once everything is available. Also I have agreed with organisers to keep a 2 weeks period between the release of the videos and the publication to make sure the Youtube Alogythm is not impacted as the activity on a video on the first few days has some impact on it's reach. We wanted to make sure publishing on RubyVideo even as embedded video would not impact that reach

**Comment by jmarsh24** [comment]
We could also automate the ingestion of content onto the server by approved channels. That way they would show up on the front page and for two weeks the could link directly to youtube and later on stay rubyvideo.dev. For instance a cron job could automatically fetch all the new videos of a channel every day.

I would love to see trending videos/topics on the front page so it becomes the source for new content.
