### ISSUE TITLE
Feedback on Posette, Sin City Ruby, Madison+ Ruby

### ISSUE THREAD

**Issue by andyatkinson** [adrienpoly/rubyvideo#223]
Hi there. Would Posette work? This was an online Postgres conference, and I presented on how we might scale up a fictional Rails app, in part by using Active Record capabilities like Horizontal Sharding.
https://www.youtube.com/watch?v=RwXJ4s2pw1A

Also, are there any contribution guidelines or past proposals on Ruby talks where video wasn't recorded? For example, we could still get featured but maybe slides only. I realize the repo is called "rubyvideo", but I do have share-able slide decks and at least one picture from two presentations this year: Sin City Ruby 2024 and Madison+ Ruby 2024, however, no video was recorded. As a speaker, being featured could bring more visibility. As a visitor, I may engage with additional types of content from presenters like slide decks when video is not available.

If any of these would be approved, I'll go through the PR process and can link this issue.

Thanks!

**Comment by andyatkinson** [comment]
Me: https://www.rubyvideo.dev/speakers/andrew-atkinson

Sin City Ruby 2024: https://andyatkinson.com/blog/2024/03/25/sin-city-ruby-2024

Madison+ Ruby 2024: https://andyatkinson.com/blog/2024/08/13/madison-plus-ruby-conference-recap

**Comment by marcoroth** [comment]
In my vision RubyVideo (or RubyEvents) will host conference talks without videos too in the future - at least at the point where we implement features like #184.
