### ISSUE TITLE
Speaker Name is misaligned in Talk Card

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#230]
![CleanShot 2024-10-17 at 13 31 32@2x](https://github.com/user-attachments/assets/b6576b15-3bdc-496b-888d-6329b94500eb)

![CleanShot 2024-10-17 at 13 31 32@2x](https://github.com/user-attachments/assets/3d4b3d17-7d04-4306-9cf1-f81540dae4da)

**Comment by jmarsh24** [comment]
fixed in #231
