### ISSUE TITLE
Vite not found

### ISSUE THREAD

**Issue by enderahmetyurt** [adrienpoly/rubyvideo#24]
Hello,

I am trying to run the project on my local. After forked the project, and bundle everything, I try to run `bin/dev` I got error below

![Screenshot 2023-06-23 at 08 40 24](https://github.com/adrienpoly/rubyvideo/assets/447588/755e5e82-68ae-4f91-8f73-5f68d228d052)

When I try to run just Vite by `bin/vite dev` I got this error. And I checked `vite` command exists in my local. 

![Screenshot 2023-06-23 at 08 38 49](https://github.com/adrienpoly/rubyvideo/assets/447588/ecc19c65-374f-4e8e-a56c-b083a43f1d1b)

What should I do fixing vite running problem? 

Thanks

**Comment by adrienpoly** [comment]
did you run `bin/setup` or `yarn install` ?

**Comment by enderahmetyurt** [comment]
Thank you. It's fixed. The problem was node version in my local. I bumped it. 🎸
