### ISSUE TITLE
Confusing documentation for contributing data

### ISSUE THREAD

**Issue by matiaskorhonen** [adrienpoly/rubyvideo#25]
The current docs for contributing data are somewhat confusing.

* It tells you to add an organisation but this doesn't match the existing data (the `railsconf` folder seems to have a mix of events, some of which are actually from Rails Conf and some that aren't)
* The docs imply that you should list YouTube playlist IDs in `<slug>/playlists.yml` **and** the individual videos in `<slug>/<event-slug>/videos.yml` which seems like a lot of manual effort for something that could be retrieved at least partially through the YouTube API. 

It would be good if the process of creating the data files was at least partially automated, even if it was just shelling out to `youtube-dl` to fetch the video IDs for a playlist to generate a YAML file with the videos IDs and titles.

I was going to add the videos for last year's Euruko but gave up due after seeing the amount of manual copy pasting of video details that I would have to do…

**Comment by adrienpoly** [comment]
thanks @matiaskorhonen I have some scripts locally that are useful to generate those files. I haven't had time to release them yet. I want to make then a bit more flexible and comprehensive. I hope to have this available this week end. Thanks for raising this point I know it is important to have a clear path forward if we want to easily gather more data

**Comment by adrienpoly** [comment]
#60 should help I am still polishing some scripts and mostly the title description parser

**Comment by adrienpoly** [comment]
#60 was merge and adds a better workflow to adding metadata
