### ISSUE TITLE
status page returns 404

### ISSUE THREAD

**Issue by jmarsh24** [adrienpoly/rubyvideo#275]
This page returns a 404 and should be fixed.

https://status.rubyvideo.dev

<img width="609" alt="image" src="https://github.com/user-attachments/assets/41a40869-d99d-433e-abe8-997710b3c7de">

**Comment by adrienpoly** [comment]
it is working for me now

![CleanShot 2024-10-22 at 21 55 35@2x](https://github.com/user-attachments/assets/cf776b5a-950c-48b2-9f06-6e3c002e5652)

I suppose Appsignal had a downtime (this page is not hosted by us, it is provided by AppSignal)
