### ISSUE TITLE
Fix navbar links

### ISSUE THREAD

**Issue by jmarsh24** [adrienpoly/rubyvideo#278]
Compare these two links and images. The sign in link shows up for the leader board but not on the other pages. I'm not sure what the intended behavior is supposed to be @adrienpoly 

https://www.rubyvideo.dev/topics
<img width="614" alt="image" src="https://github.com/user-attachments/assets/f4ce13b6-be00-4673-bff3-026bdddf48f3">

https://www.rubyvideo.dev/leaderboard
<img width="686" alt="image" src="https://github.com/user-attachments/assets/c02693eb-396f-44d1-a0c6-2e9ebb9f68b9">

**Comment by marcoroth** [comment]
@jmarsh24 isn't that because you aren't signed in the first pic and you are signed in the second?

**Comment by jmarsh24** [comment]
@marcoroth I don't think so, If you log out. and click between them, then you will see the links change.

**Comment by jmarsh24** [comment]
https://share.cleanshot.com/z0ZMDMrq

**Comment by marcoroth** [comment]
ha! I'm wondering if this is served from the Turbo cache client-side 🤔

**Comment by jmarsh24** [comment]
@marcoroth I found the issue. The page is cached with an etag using the fresh_when helper method

https://github.com/jmarsh24/rubyvideo/blob/95c2e71973c62d034c01d004f933cc8ce4440186/app/controllers/leaderboard_controller.rb#L16

**Comment by marcoroth** [comment]
Ah, interesting. Is there a way how we can invalidate the cache when a user signs in.

**Comment by jmarsh24** [comment]
fixed by #319
