### ISSUE TITLE
Extend Suggestable Fields

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#292]
While looking at https://github.com/adrienpoly/rubyvideo/blob/26129eb27ea1360be8ee8e978d4721be2a54b8ac/app/controllers/speakers_controller.rb#L61-L68 for #279 I realized that `anonymous` and `signed_in` users can only suggest the `github` column. I was wondering if we should allow all fields to be suggested since they are reviewed anyway if it's a non-owner and non-admin.

**Comment by adrienpoly** [comment]
yes not sure why I made it like that.
