### ISSUE TITLE
Introduce YAML formatter for consistent YAML files 

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#308]
Let's agree on a package to use for formatting our YAML files so that touching a YAML file in an editor that auto-formats doesn't generate a huge diff.

**Comment by adrienpoly** [comment]
So far I have been using prettier for that 

https://github.com/adrienpoly/rubyvideo/blob/b4a71107e7a55934f6c258ef33c910447b50e332/scripts/dump_speakers.rb#L40

we could see how to configure it by default in the project and add it to the bin/lint task

**Comment by marcoroth** [comment]
Opened #309 for that 👍🏼
