### ISSUE TITLE
Enforce modals for modal endpoints

### ISSUE THREAD

**Issue by jmarsh24** [adrienpoly/rubyvideo#315]
A user has the possibility to navigate to the users#new endpoint and also open the modal which leads to a duplicate modal and page navigation. As a user, I would expect to only be able to view the session#new within the context of a modal.

![CleanShot 2024-10-29 at 10 14 04@2x](https://github.com/user-attachments/assets/192d8069-374e-4c7e-91f6-0a1cc101475c)

**Comment by adrienpoly** [comment]
Good point. I though that I included that when I added the remote modal concern but I didn’t copied that part from my other project. 

Something to add definitely
