### ISSUE TITLE
Fix broken thumbnails on Talks#Show page

### ISSUE THREAD

**Issue by jmarsh24** [adrienpoly/rubyvideo#328]
The avatar thumbnails are all broken on the Talks#show page as highlighted in the pictures below.

A![CleanShot 2024-10-30 at 10 37 46@2x](https://github.com/user-attachments/assets/996e2e10-0582-4bf3-9d04-f225227857ef)

![CleanShot 2024-10-30 at 10 33 46@2x](https://github.com/user-attachments/assets/b04df974-8590-4f1d-875e-ff71860886d2)

**Comment by marcoroth** [comment]
I think GitHub is been having some issues today and yesterday.

**Comment by jmarsh24** [comment]
Ahhh they are not working again. Maybe we should consider actually storing the images on our end?

**Comment by marcoroth** [comment]
I added fallback avatars in #324 yesterday, so we st least get initials.

**Comment by adrienpoly** [comment]
Pulling images from GitHub was the most simple solution at the beginning but I agree we should do something about it. Will open a new issue
