### ISSUE TITLE
RailsConf 2022 talks are indexed twice

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#33]
It seems like all the RailsConf 2022 videos are indexed twice on the production application, they don't appear twice in the dataset.

| Example [Kevin Lesht](https://rubyvideo.dev/speakers/kevin-lesht) | Example [Andrew Atkinson](https://rubyvideo.dev/speakers/andrew-atkinson) | 
| --- | --- |
| ![Screenshot 2023-06-24 at 23 39 23](https://github.com/adrienpoly/rubyvideo/assets/6411752/42870779-fb7a-4776-83d3-214557367dfa) | ![Screenshot 2023-06-24 at 23 39 10](https://github.com/adrienpoly/rubyvideo/assets/6411752/b809efa4-5e37-4b2b-aa30-42b8fb6b7ade) |

Looking at the talks, one of them is assigned to the RailsConf 2022 conference while the other isn't assigned to any conference. This probably just need to be cleaned up in the production database, so there is no code change needed.

**Comment by adrienpoly** [comment]
good catch will look into the prod db as soon as I have a better internet connection (✈️)
