### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#341]
Currently RubyVideo doesn't have a favicon, let's agree on a logo and add one 😊

**Comment by marcoroth** [comment]
I've been using this logo for some of the artwork, but I'm not sure if want to continue using it 😅 

<img width="30%" src="https://github.com/user-attachments/assets/338e9f7d-36c2-4dc3-ad43-69a83a8bde5f"/>

**Comment by marcoroth** [comment]
Agreed, I was just thinking it's better than nothing and since we already use it for some we might as well use it for the favicon until we have another/better one.

**Comment by adrienpoly** [comment]
Sure let’s go
