### ISSUE TITLE
Ability to mark talk as seen

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#364]
If you've seen a talk it would be cool to be able to "mark it as seen". When signed in we could visually show to the user that they've already seen this talk. 

Maybe we can even ask the user if they've seen it in-person at the event or online.

**Comment by nicogaldamez** [comment]
Happy to help with this!

What do you think about having a button next to edit button:
<img width="854" alt="image" src="https://github.com/user-attachments/assets/8ec099ba-aac2-427d-a6f8-530468deed52">
![image](https://github.com/user-attachments/assets/9da35214-d37f-4a16-8571-51d67bbda7a6)

**Comment by adrienpoly** [comment]
I think we need two new buttons. Bookmark (add to favorite) and mark as watched. The location looks good to me but I feel like those two buttons should be grouped somewhere and we might be lacking a bit of space here. or we have to move the edit button ?

**Comment by marcoroth** [comment]
I guess depending on how we (re-)arrange it we can look how YouTube is doing it:

![CleanShot 2024-11-05 at 23 25 07](https://github.com/user-attachments/assets/29006303-0876-431b-a8c1-e044a4be512b)

**Comment by nicogaldamez** [comment]
Sounds good! How about we go ahead with adding the "Mark as watched" button now, then handle the Bookmark button and layout adjustments in a separate PR?

"Mark as Watched / Unmark as Watched" texts sound good to you?

**Comment by adrienpoly** [comment]
> Sounds good! How about we go ahead with adding the "Mark as watched" button now, then handle the Bookmark button and layout adjustments in a separate PR?

Yes sure just go with one button first 

> "Mark as Watched / Unmark as Watched" texts sound good to you?

I feel it is a bit long but I cannot find anything real better so for me let's go like that

**Comment by marcoroth** [comment]
Here's an idea on how we could keep it short:

![Talk Show Interaction Buttons@2x](https://github.com/user-attachments/assets/ff4e96c8-ee46-426b-9e37-837e651f3204)

**Comment by marcoroth** [comment]
Resolved via #383
