### ISSUE TITLE
Add empty stage to Favourites page

### ISSUE THREAD

**Issue by enderahmetyurt** [adrienpoly/rubyvideo#371]
There would be a empty message or something when a user doesn't have any favourite.

![Screenshot 2024-11-05 at 08 35 52](https://github.com/user-attachments/assets/3b3ee1e9-113e-4657-91e7-9e163d62cfc0)

**Comment by enderahmetyurt** [comment]
I can look at it 🙏

**Comment by adrienpoly** [comment]
Yes please do

I like the CSS approach for empty state using `only-child` selector

https://boringrails.com/articles/css-tips-and-tricks-hotwire/

but just a suggestion if it is applicable
