### ISSUE TITLE
Reduce CI test time

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#391]
The test job now takes about 3 minutes to run. It is ok but given the size of the app it feels a lot. Mot of the time is spent in the seed test. Those tests are important as they ensure seed will run smoothly but as the data is growing the test suite will become slower and slower.

One solution I could see is that we have a list of event that we consider done and that we don't seed over and over every time. and if needed we have the action in the admin to do so.

Happy to hear other suggestions

**Comment by marcoroth** [comment]
I think we just have to improve the way we seed. There's probably a lot we can improve and optimize.

**Comment by marcoroth** [comment]
We might be able to close this issue now after merging #392, depending on how you feel @adrienpoly

**Comment by adrienpoly** [comment]
yes much better now. I  might in the future extract the seed test to its own workflow but let's close this now
