### ISSUE TITLE
Talks thumbnail image alt attribute is wrong

### ISSUE THREAD

**Issue by manishElitmus** [adrienpoly/rubyvideo#41]
### Problem

The thumbnail images for each talk on the talks page render with the img tag, but the alt attribute is incorrect. This is shown in the screenshot below.

<img width="1428" alt="image" src="https://github.com/adrienpoly/rubyvideo/assets/131235135/5375a115-1a40-40d6-8764-44c2de5ceefa">

**Comment by manishElitmus** [comment]
@adrienpoly Can I take this one?

**Comment by adrienpoly** [comment]
@manishElitmus still interested to tackle this one?

**Comment by manishElitmus** [comment]
> @manishElitmus still interested to tackle this one?

Yes @adrienpoly I'll send a PR

**Comment by adrienpoly** [comment]
thanks for reporting the issue I was working on that card and fixed this with https://github.com/adrienpoly/rubyvideo/commit/6ee35207d4a1c4fa7bf98fdd33f3f544177e7584
