### ISSUE TITLE
YouTube Sign-in required in some conditions, no link to source to workaround

### ISSUE THREAD

**Issue by ttilberg** [adrienpoly/rubyvideo#410]
From my work VPN, I'm unable to watch embedded YouTube videos without being presented with the "Sign-in to confirm you are not a bot" error.

<img width="900" alt="image" src="https://github.com/user-attachments/assets/1ec4b85f-8c80-417f-9534-af1b429d932b">

Over at Real Youtube, my account is currently signed in and I am able to watch videos, but there isn't an easy way to get there from the video index.

I propose adding a link to the hosted source material to allow users to give a workaround to resolve this type of issue. It also adds transparency with video hosting attribution.

**Comment by adrienpoly** [comment]
I agree this is something I wanted to add to as some people might prefer to watch and save on YouTube in their watch later list by example. 

Happy to take a PR for that
