### ISSUE TITLE
In talk show view, clicking speaker tab sends tab content to bottom of page

### ISSUE THREAD

**Issue by ttilberg** [adrienpoly/rubyvideo#411]
When I click the speaker tab here:
<img width="931" alt="image" src="https://github.com/user-attachments/assets/df712b01-12ff-49a6-be31-f5e38628b51f">

The content is sent to the bottom of the page:
![image](https://github.com/user-attachments/assets/a85596e7-ece4-474b-8aca-5a8fe5a58154)

This seems to be caused by the `.avatar` class in this container:

![image](https://github.com/user-attachments/assets/424ca31f-1e31-4bf2-9d98-c8d1e0ccd7ee)

When I deselect `.avatar>div: aspect-ratio: 1 / 1` the layout is fixed.

Safari 17.6 MacOS

**Comment by adrienpoly** [comment]
We definitely noticed something strange with this tab. Thanks for your investigations. It is very helpful

**Comment by marcoroth** [comment]
I feel like we should just ditch the hacky daisyUI tabs and replace them with proper tabs using JavaScript.
