### ISSUE TITLE
Show Talk Language on Talk Show Page

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#450]
Right now we only show the talk language in the talk card, but it would make sense to also show it somewhere on the talk show page.

**Comment by aamfahim** [comment]
I gave it a go. Added it to the description of the talk and only if it's not `English`. Let me know what you think!

![new implementation](https://github.com/user-attachments/assets/0fa732ba-76c7-450b-82ad-a8ee69fabf3e)

**Comment by marcoroth** [comment]
Thank you, @aamfahim! 🚀
