### ISSUE TITLE
Add a burger menu in mobile

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#6]
In mobile there is currently no menu available. We should have a burger menu with a dropdown available

**Comment by code-death** [comment]
Hello Adrien can I work on this issue and can you please tell what are the contribution guidelines for this as I couldn't find anything related to issues, branches or PRs in the existing guidelines

**Comment by awalsh3** [comment]
Hello! Wondering if I could take a stab at this? I am new to the community. No worries if it's already in progress!
