### ISSUE TITLE
enhance links in video description 

### ISSUE THREAD

**Issue by yshmarov** [adrienpoly/rubyvideo#66]
- highlight links
- add target _blank
- maybe add referrer?

let me know if you would like to have it and I can try making a PR

<img width="1308" alt="Screenshot 2023-10-23 at 23 36 41" src="https://github.com/adrienpoly/rubyvideo/assets/13472945/69412161-7015-4717-ae5c-5b245edbfe71">

**Comment by adrienpoly** [comment]
Yessssssss

**Comment by marcoroth** [comment]
I think this might be solved now, as links are now being renders as `<a>` tags in descriptions.

![CleanShot 2024-08-08 at 10 16 08](https://github.com/user-attachments/assets/5eb09f62-599b-4ff7-a5f5-127fdaec405a)

**Comment by adrienpoly** [comment]
yes probably added the auto link at some point

https://github.com/adrienpoly/rubyvideo/blob/808947c8ec2a80f29118e58763ffd85a05238806/app/views/talks/_talk.html.erb#L39
