### ISSUE TITLE
Create the event page

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#7]
The event page should be a page displaying on la left the event information (date web site location) and on the right the videos from that event.

**Comment by dedemenezes** [comment]
Hey @adrienpoly, I found your website very interesting and I'm looking forward to start contributing to open-source projects.  Do you have a contribution guideline? Also, do you have a layout template for this event page or it is also part of the task?
Thank you in advance

**Comment by adrienpoly** [comment]
As a first step I think you can use part of the layout of the speaker page
Event info on the right and the list of talks 

<img width="1512" alt="CleanShot 2023-06-20 at 15 12 46@2x" src="https://github.com/adrienpoly/rubyvideo/assets/7847244/5fdf3d41-1ce7-4efc-9cf5-a0e72bae3bb3">

As they could be much more talks than on the speaker page you should either have a pagination or an infinite scroll 
It would be nice to have the search also scoped for this particular event

Doesn't have to come all at once, just throwing some ideas

**Comment by dedemenezes** [comment]
Nice ideas. This layout can be a good starting point and I agree with pagination or infinite scrolling. 
I'll work on it later this week. I hope by the weekend I can share some updates in here. 
Thank you for assigning me

**Comment by dedemenezes** [comment]
Hey @adrienpoly, all good? Did you abandoned this idea to add an event page? Let me know if there is something that I should do different or even redo in case the app has move into a new direction to use still ViewComponents and so on
