### ISSUE TITLE
Fix the back navigation 

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#8]
The back navigation doesn't get me back to where I was.

Two reproduction case:

### Navigation
1. navigate to /talks
2. select page 2
3. select a video
4. press back to the list

The user is taken back to the first page, it should be the second page.

### Search

1. navigate to /talks
2. search for something
3. select a video
4. press back to the list

Once again we should come back to the initial search results.
relates to #4

**Comment by Ukaypromise** [comment]
I would love to handle this issue.

**Comment by adrienpoly** [comment]
sure all yours @Ukaypromise

**Comment by Ukaypromise** [comment]
Thanks @adrienpoly

**Comment by adrienpoly** [comment]
closed by #26
